### ISSUE TITLE
screensaver selection

### ISSUE THREAD

**Issue by exeding** [ralph-irving/jivelite#1]
Hey ralph,

jivelite is awesome so far.
But can you tell me how to select a screensaver in the options of jivelite?
help says: " press middle button to select screensaver" but im using a raspberry pi model B with keyboard attached. What button to use to select a screenseaver (i tried them all but nothing happens) .
Can you give me a hint or is that feature not avail in my setup?

kind regards and sorry for my dumb question.
exeding

**Comment by ralph-irving** [comment]
Settings->Screen->Screensavers from jivelite allows you choose when and which saver is used.
