### ISSUE TITLE
Change behavior of touch

### ISSUE THREAD

**Issue by acoushawk** [ralph-irving/jivelite#13]
Is there any way to change the behavior of selecting a song? I want it to add the song to the end of the playlist by default instead of creating a new playlist with just the song. Not sure exactly where to find this at in the code.

Any help would be very much appreciated!!

**Comment by michaelherger** [comment]
This is not a function of jivelite, but server driven. Check out LMS 7.9: there's a "defeat to play" feature which would give you a choice if there was already something playing, rather than wipe the queue and start the new track.
