### ISSUE TITLE
Help please - keyboard

### ISSUE THREAD

**Issue by IAmLostForWords** [ralph-irving/jivelite#15]
Hello,

I am having an issue on my raspbian based pCP and I can not find a solution to it: while on the console my non-us keyboard layout perfectly works, within jivelite, I only have the US qwerty layout.
Could you please advise or advise where to find a solution or request for such?
I tried googling, tweaking pcp / tiny core etc. to no avail.

Thanks and whishing you a happy 2018
Marcus

**Comment by ralph-irving** [comment]
Hi Marcus,  Your issue is unclear to me.  Does your non-us keyboard work or not when jivelite is running on the console?

**Comment by IAmLostForWords** [comment]
Hi Ralph

Thanks for responding. Within jivelite: only U.S. keyboard. When remotely logging in via ssh: german keyboard layout.

Marcus

**Comment by ralph-irving** [comment]
jivelite only reads keys from the console keyboard when using the framebuffer in pcp.  Using ssh to control jivelite is not supported.

**Comment by IAmLostForWords** [comment]
that is a misunderstanding: jivelite is running within pCP, started from the console. I do not start / control it via ssh. When jivelite is started within console, I only have the US keyboard. When remotely logging in I have my German keys. Should I assume that the default console configuration is different from the shell configuration for ssh?

**Comment by ralph-irving** [comment]
Yes they are different.
When you connect using ssh you inherit the locale of the remote machine. pcp currently only supports the us keyboard from the console.

**Comment by IAmLostForWords** [comment]
Thanks for the quick responses! To understand correctly: no chance of modifying /etc/sysconfig/keyboard or similar tricks?

**Comment by IAmLostForWords** [comment]
sorry /etc/sysconfig/keymap of course

**Comment by ralph-irving** [comment]
There's no way that I'm aware.

**Comment by ralph-irving** [comment]
I just came across this while researching another keyboard issue.

http://distro.ibiblio.org/tinycorelinux/faq.html#keyboard

**Comment by IAmLostForWords** [comment]
Hi, yes, I have seen that too. But the kmaps extension is not part of pCP. But in pCP there are under /usr/locale/share/keymaps keymap definitions. These can be dumped to the required binary format using the 'loadkeys -b' command to /usr/share/kmap. Then those can be loaded using loadkmap.
In order to make that persistent:
0. dump preferrably 'sudo gunzip /usr/locale/share/keymaps/WHATEVER.map.gz && sudo loadkeys -b /usr/locale/share/keymaps/WHATEVER.map > /usr/share/kmap/WHATEVER.kmap
1. Add the reference to the kmap file to /opt/.filetool.lst
2. Add a call to 'loadkmap < /usr/share/kmap/de-latin1-nodeadkeys.kmap' to /opt/bootlocal.sh
3. persist with 'sudo filetool.sh -b'
4. reboot
seems to work

**Comment by IAmLostForWords** [comment]
Maybe should add that some of the maps are dependent. If for example you use de-latin1-nodeadkeys, you will have to gunzip the de-latin1 before, it seems
