### ISSUE TITLE
Jivelite controling remote squeezelite?

### ISSUE THREAD

**Issue by NohWayJose** [ralph-irving/jivelite#16]
Hi Ralph, 

I just want to see if Jivelite will address my use case. (Sorry if _Git Issues_ isn't the place to ask. If there's a more suitable place, please let me know where, Thanks)

I have my music served from _LMS_ on a _Synology NAS_ on my wired network. In my bathroom, I have ceiling speakers linked to a _Pi Zero W_, running _PiCorePlayer_ & _Squeezelite_ with a _JustBoom Amp Zero_ - This is mounted well away from water, in a cupboard. I can control this well, using Squeezer on my Android phone to play music from the NAS _LMS_. 

I would prefer to control it from my _Pi 3B_ with a _Pimoroni TFT_ 60fps 80x51mm touchscreen, in a waterproof mounting, near the bath.

My main concerns are:
a) will _Jivelite_ be able to drive this screen? 
and
b) can _Jivelite_ on the _Pi 3B_ control a non-local instance of _Squeezelite_ (ie, the one on the _Pi Zero W_)?

Thanks, Greg

**Comment by ralph-irving** [comment]
Yes, jivelite can control a remote squeezelite instance.  Depending on what OS you choose to run on the rpi and the screen resolution it could work.  Please join the slimdevices forums at https://forums.slimdevices.com  There's a plethora of information on using touch screens on the rpi and jivelite.
