### ISSUE TITLE
[feature request] add the ability to add custom commands to send from within jivelite

### ISSUE THREAD

**Issue by fsyy** [ralph-irving/jivelite#2]
Hi,

it would be nice to have a option to create 'touchable' custom commands to send from within jivelite.

I could add some commands to switch on/off lights, to start my wake on lan capable computer and so on.

Thanks for listening

fsyy

**Comment by ralph-irving** [comment]
This thread is currently exploring the feature.
http://forums.slimdevices.com/showthread.php?105675-Execute-script-on-server-from-lua-applet-on-Squeezeplay-(or-Duet-Controller)
It's not something that I need.
