### ISSUE TITLE
Scrolling and touch becomes unresponsive

### ISSUE THREAD

**Issue by trs79** [ralph-irving/jivelite#5]
I'm using Jivelite on a Raspberry PI 3 with the official 7" touch screen. When I view a large list (like artists or albums) and rapidly swipe to scroll up and down, randomly the list will go the the top and touching or swiping no longer has any effect. The only way to reset it is to press the back button then go back to the list.

**Comment by ralph-irving** [comment]
I've been unable to reproduce the same behaviour.
