### ISSUE TITLE
Unable to open a console terminal

### ISSUE THREAD

**Issue by alidaf** [ralph-irving/jivelite#7]
I have a framebuffer device working for a 256x64 oled display. Logging in via ssh and starting jivelite gives an error "Unable to open a console terminal".

I have fbcon=map:10 in /boot/cmdline.txt.
I have /dev/fb0 mapped onto /dev/fb1 (which is where the oled display is) and have been able to play videos with omxplayer and run fbtest with no problems.
fbset -v reports the geometry of /dev/fb0 as 656x416.

I would have expected to at least see a partial display.

Is this due to skin size (I want to create a specific 256x64 skin) or another issue?

**Comment by alidaf** [comment]
sudo works!

Is there a way to specify the settings by editing a file rather than having to attach a keyboard to the device?
Can I avoid having to use sudo by starting it as a service?

**Comment by ralph-irving** [comment]
You would need to give the regular use permissions to open /dev/fb? if you don't want to use sudo.
